### ISSUE TITLE
I have been trying to install the module with no luck

### ISSUE THREAD

**Issue by manu354** [allenluce/mmap-object#13]
I dont Know what is the real problem. Looks like its trying to execute node but not finding it maybe. Dunno any ideas?

Error: 
```
npm install mmap-object

> mmap-object@1.3.5 install F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/allenluce/mmap-object/releases/downlo
ad/1.3.5/mmap-object-v1.3.5-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mmap-object@1.3.5 and node@8.1.3 (node-v57 ABI)
 (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m
" switch.
  mmap-object.cc
  win_delay_load_hook.cc
..\mmap-object.cc(11): fatal error C1083: Cannot open include file: 'boost/interprocess/managed_m
apped_file.hpp': No such file or directory [F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object
\build\mmap-object.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code:
 1
gyp ERR! stack     at ChildProcess.onExit (F:\ARBITTREX\crypto-arb-priv\node_modules\node-gyp\lib\
build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "F:\\Program Files\\nodejs\\node.exe" "F:\\ARBITTREX\\crypto-arb-priv\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\ARBITTREX\\crypto-arb-
priv\\node_modules\\mmap-object\\lib\\mmap-object.node" "--module_name=mmap-object" "--module_path
=F:\\ARBITTREX\\crypto-arb-priv\\node_modules\\mmap-object\\lib"
gyp ERR! cwd F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'F:\Program Files\nodejs\node.exe F:\ARBITTREX\cr
ypto-arb-priv\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=F:\ARBITTRE
X\crypto-arb-priv\node_modules\mmap-object\lib\mmap-object.node --module_name=mmap-object --module
_path=F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object\lib' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\ARBITTREX\crypto-arb-priv\node_modules
\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:
5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "F:\\Program Files\\nodejs\\node.exe" "F:\\ARBITTREX\\crypto-arb-priv\\n
ode_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object
node-pre-gyp ERR! node -v v8.1.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok
Failed to execute 'F:\Program Files\nodejs\node.exe F:\ARBITTREX\crypto-arb-priv\node_modules\node
-gyp\bin\node-gyp.js build --fallback-to-build --module=F:\ARBITTREX\crypto-arb-priv\node_modules\
mmap-object\lib\mmap-object.node --module_name=mmap-object --module_path=F:\ARBITTREX\crypto-arb-p
riv\node_modules\mmap-object\lib' (1)
npm WARN cryptocurrency-arbitrage@1.4.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmap-object@1.3.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmap-object@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manu\AppData\Roaming\npm-cache\_logs\2017-09-16T19_45_14_634Z-debug.log
```

**Comment by allenluce** [comment]
It's looking for Boost headers:

    ..\mmap-object.cc(11): fatal error C1083: Cannot open include file: 'boost/interprocess/managed_mapped_file.hpp': No such file or directory [F:\ARBITTREX\crypto-arb-priv\node_modules\mmap-object\build\mmap-object.vcxproj]

You may have to [install or re-install Boost](http://www.boost.org/doc/libs/1_65_1/more/getting_started/windows.html).
