### ISSUE TITLE
Problem building on Linux ARM

### ISSUE THREAD

**Issue by ajcanterbury** [allenluce/mmap-object#17]
I'm trying to install the module on a Linux ARM platform but I'm running into a symbol versioning issue:

```
/usr/bin/ld: Release/obj.target/mmap-object.node: No symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'
/usr/bin/ld: final link failed: Nonrepresentable section on output
...
```

**Comment by allenluce** [comment]
Hi @ajcanterbury, what version of node are you using?

**Comment by ajcanterbury** [comment]
8.12

**Comment by allenluce** [comment]
I've pushed a fix that should take care of this and have also populated the release with Arm binaries. Please have another go at this and let me know how it works out.

**Comment by ajcanterbury** [comment]
Awesome, thank you! I'll try it out tonight and report back.

**Comment by ajcanterbury** [comment]
It appears to be working except when I tested on an armv7 (32bit); 46 passing, 7 failing. With output:
  

> 1) mmap-object
>        Writer
>          avoids getting too big when rewriting the same key over and over:
>      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/pi/code/mmap-object/test/test-mmap-object.js)
>   
> 
>   2) mmap-object
>        Informational methods:
>          has get_free_memory:
> 
>       AssertionError: expected 8264 to be above 12430
>       + expected - actual
> 
>       -8264
>       +12430
>       
>       at Context.<anonymous> (test/test-mmap-object.js:186:37)
> 
>   3) mmap-object
>        Informational methods:
>          has bucket_count:
> 
>       AssertionError: expected 17 to equal 4
>       + expected - actual
> 
>       -17
>       +4
>       
>       at Context.<anonymous> (test/test-mmap-object.js:196:42)
> 
>   4) mmap-object
>        Informational methods:
>          has max_bucket_count:
> 
>       AssertionError: expected 1031 to equal 512
>       + expected - actual
> 
>       -1031
>       +512
>       
>       at Context.<anonymous> (test/test-mmap-object.js:208:24)
> 
>   5) mmap-object
>        Informational methods:
>          has load_factor:
> 
>       AssertionError: expected 0 to equal 0.625
>       + expected - actual
> 
>       -0
>       +0.625
>       
>       at Context.<anonymous> (test/test-mmap-object.js:213:24)
> 
>   6) mmap-object
>        Still can read old format
>          "before all" hook:
>      Error: /home/pi/code/mmap-object/testdata/previous-format-linux-arm.bin: No such file or directory
>       at Context.<anonymous> (test/test-mmap-object.js:484:24)
> 
>   7) mmap-object
>        Still can read old format
>          "after all" hook:
>      TypeError: Cannot read property 'close' of undefined
>       at Context.<anonymous> (test/test-mmap-object.js:488:22)
>
